services:
  minio:
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data

  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: algohub
      MYSQL_USER: algohub
      MYSQL_PASSWORD: algohub

  judge-core:
    image: libingzhuang/judge-core:v1.1
    ports:
      - "50051:9000"
  app:
    image: ividernvi/algohub-backend:latest-test
    environment:
      - ALGOHUB_MYSQL_HOSTNAME=db
      - ALGOHUB_MINIO_ENDPOINT=minio:9000
      - ALGOHUB_JUDGE_RPC_ENDPOINT=judge-core:9000
    ports:
      - "8080:8080"
      - "8443:8443"
    volumes:
      - ./conf/cert:/root/conf/cert:ro # Mounting SSL certificates
    depends_on:
      - db
      - minio
      - judge-core
